---

# Vagrant configuration.

vagrant_box: "beet/dev"
vagrant_box_version: ">= 0.3.374"
vagrant_ip: 192.168.88.88



# Beetbox configuration.

beet_domain: d8.ddns.net
beet_root: "{{ beet_base }}/docroot"



# Shout configuration.

shout_home: "{{ beet_base }}/.shout"
shout_port: 7000
shout_display_network: "false"
shout_defaults_nick: ""
shout_defaults_username: ""
shout_defaults_realname: ""
shout_defaults_join: "#drupal, #drupal-contribute, #drupalcon"



# Firewall configuration.

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "7000"
  - "8025"
